package com.appcompras.config;

public enum ApiErrorCode {
	INGREDIENT_NOT_FOUND,
	INVALID_INGREDIENT_UNIT,
	PLAN_DUPLICATE_SLOT,
	PLAN_RECIPE_NOT_FOUND,
	PLAN_SLOT_OUT_OF_RANGE,
	SHOPPING_ITEM_INGREDIENT_REQUIRED,
	SHOPPING_ITEM_INVALID_PACKAGE_AMOUNT,
	SHOPPING_ITEM_INVALID_SORT_ORDER,
	SHOPPING_ITEM_INVALID_SUGGESTED_PACKAGES,
	SHOPPING_ITEM_NOTE_TOO_LONG,
	SHOPPING_ITEM_PACKAGE_FIELDS_INCOMPLETE
}
